/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGymMembersRouteImport } from './routes/app.gym.members'
import { Route as AppGymOverviewRouteImport } from './routes/app.gym.overview'
import { Route as AppGymSettingsRouteImport } from './routes/app.gym.settings'
import { Route as AppSchoolBranchesRouteImport } from './routes/app.school.branches'
import { Route as AppSchoolCustomBillingRouteImport } from './routes/app.school.custom-billing'
import { Route as AppSchoolFeeStructuresRouteImport } from './routes/app.school.fee-structures'
import { Route as AppSchoolOverviewRouteImport } from './routes/app.school.overview'
import { Route as AppSchoolPaymentsRouteImport } from './routes/app.school.payments'
import { Route as AppSchoolRemindersRouteImport } from './routes/app.school.reminders'
import { Route as AppSchoolSettingsRouteImport } from './routes/app.school.settings'
import { Route as AppSchoolStudentsRouteImport } from './routes/app.school.students'
import { Route as AppGymPayIdRouteImport } from './routes/app.gym.pay.$id'
import { Route as AppSchoolPayIdRouteImport } from './routes/app.school.pay.$id'
import { Route as AppSchoolPayChallanIdRouteImport } from './routes/app.school.pay.challan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGymMembersRoute = AppGymMembersRouteImport.update({
  id: '/app/gym/members',
  path: '/app/gym/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGymOverviewRoute = AppGymOverviewRouteImport.update({
  id: '/app/gym/overview',
  path: '/app/gym/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGymSettingsRoute = AppGymSettingsRouteImport.update({
  id: '/app/gym/settings',
  path: '/app/gym/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolBranchesRoute = AppSchoolBranchesRouteImport.update({
  id: '/app/school/branches',
  path: '/app/school/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolCustomBillingRoute = AppSchoolCustomBillingRouteImport.update({
  id: '/app/school/custom-billing',
  path: '/app/school/custom-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolFeeStructuresRoute = AppSchoolFeeStructuresRouteImport.update({
  id: '/app/school/fee-structures',
  path: '/app/school/fee-structures',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolOverviewRoute = AppSchoolOverviewRouteImport.update({
  id: '/app/school/overview',
  path: '/app/school/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolPaymentsRoute = AppSchoolPaymentsRouteImport.update({
  id: '/app/school/payments',
  path: '/app/school/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolRemindersRoute = AppSchoolRemindersRouteImport.update({
  id: '/app/school/reminders',
  path: '/app/school/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolSettingsRoute = AppSchoolSettingsRouteImport.update({
  id: '/app/school/settings',
  path: '/app/school/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolStudentsRoute = AppSchoolStudentsRouteImport.update({
  id: '/app/school/students',
  path: '/app/school/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGymPayIdRoute = AppGymPayIdRouteImport.update({
  id: '/app/gym/pay/$id',
  path: '/app/gym/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolPayIdRoute = AppSchoolPayIdRouteImport.update({
  id: '/app/school/pay/$id',
  path: '/app/school/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchoolPayChallanIdRoute = AppSchoolPayChallanIdRouteImport.update({
  id: '/app/school/pay/challan/$id',
  path: '/app/school/pay/challan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/gym/members': typeof AppGymMembersRoute
  '/app/gym/overview': typeof AppGymOverviewRoute
  '/app/gym/settings': typeof AppGymSettingsRoute
  '/app/school/branches': typeof AppSchoolBranchesRoute
  '/app/school/custom-billing': typeof AppSchoolCustomBillingRoute
  '/app/school/fee-structures': typeof AppSchoolFeeStructuresRoute
  '/app/school/overview': typeof AppSchoolOverviewRoute
  '/app/school/payments': typeof AppSchoolPaymentsRoute
  '/app/school/reminders': typeof AppSchoolRemindersRoute
  '/app/school/settings': typeof AppSchoolSettingsRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/gym/pay/$id': typeof AppGymPayIdRoute
  '/app/school/pay/$id': typeof AppSchoolPayIdRoute
  '/app/school/pay/challan/$id': typeof AppSchoolPayChallanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/gym/members': typeof AppGymMembersRoute
  '/app/gym/overview': typeof AppGymOverviewRoute
  '/app/gym/settings': typeof AppGymSettingsRoute
  '/app/school/branches': typeof AppSchoolBranchesRoute
  '/app/school/custom-billing': typeof AppSchoolCustomBillingRoute
  '/app/school/fee-structures': typeof AppSchoolFeeStructuresRoute
  '/app/school/overview': typeof AppSchoolOverviewRoute
  '/app/school/payments': typeof AppSchoolPaymentsRoute
  '/app/school/reminders': typeof AppSchoolRemindersRoute
  '/app/school/settings': typeof AppSchoolSettingsRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/gym/pay/$id': typeof AppGymPayIdRoute
  '/app/school/pay/$id': typeof AppSchoolPayIdRoute
  '/app/school/pay/challan/$id': typeof AppSchoolPayChallanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/gym/members': typeof AppGymMembersRoute
  '/app/gym/overview': typeof AppGymOverviewRoute
  '/app/gym/settings': typeof AppGymSettingsRoute
  '/app/school/branches': typeof AppSchoolBranchesRoute
  '/app/school/custom-billing': typeof AppSchoolCustomBillingRoute
  '/app/school/fee-structures': typeof AppSchoolFeeStructuresRoute
  '/app/school/overview': typeof AppSchoolOverviewRoute
  '/app/school/payments': typeof AppSchoolPaymentsRoute
  '/app/school/reminders': typeof AppSchoolRemindersRoute
  '/app/school/settings': typeof AppSchoolSettingsRoute
  '/app/school/students': typeof AppSchoolStudentsRoute
  '/app/gym/pay/$id': typeof AppGymPayIdRoute
  '/app/school/pay/$id': typeof AppSchoolPayIdRoute
  '/app/school/pay/challan/$id': typeof AppSchoolPayChallanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/gym/members'
    | '/app/gym/overview'
    | '/app/gym/settings'
    | '/app/school/branches'
    | '/app/school/custom-billing'
    | '/app/school/fee-structures'
    | '/app/school/overview'
    | '/app/school/payments'
    | '/app/school/reminders'
    | '/app/school/settings'
    | '/app/school/students'
    | '/app/gym/pay/$id'
    | '/app/school/pay/$id'
    | '/app/school/pay/challan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/gym/members'
    | '/app/gym/overview'
    | '/app/gym/settings'
    | '/app/school/branches'
    | '/app/school/custom-billing'
    | '/app/school/fee-structures'
    | '/app/school/overview'
    | '/app/school/payments'
    | '/app/school/reminders'
    | '/app/school/settings'
    | '/app/school/students'
    | '/app/gym/pay/$id'
    | '/app/school/pay/$id'
    | '/app/school/pay/challan/$id'
  id:
    | '__root__'
    | '/'
    | '/app/gym/members'
    | '/app/gym/overview'
    | '/app/gym/settings'
    | '/app/school/branches'
    | '/app/school/custom-billing'
    | '/app/school/fee-structures'
    | '/app/school/overview'
    | '/app/school/payments'
    | '/app/school/reminders'
    | '/app/school/settings'
    | '/app/school/students'
    | '/app/gym/pay/$id'
    | '/app/school/pay/$id'
    | '/app/school/pay/challan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppGymMembersRoute: typeof AppGymMembersRoute
  AppGymOverviewRoute: typeof AppGymOverviewRoute
  AppGymSettingsRoute: typeof AppGymSettingsRoute
  AppSchoolBranchesRoute: typeof AppSchoolBranchesRoute
  AppSchoolCustomBillingRoute: typeof AppSchoolCustomBillingRoute
  AppSchoolFeeStructuresRoute: typeof AppSchoolFeeStructuresRoute
  AppSchoolOverviewRoute: typeof AppSchoolOverviewRoute
  AppSchoolPaymentsRoute: typeof AppSchoolPaymentsRoute
  AppSchoolRemindersRoute: typeof AppSchoolRemindersRoute
  AppSchoolSettingsRoute: typeof AppSchoolSettingsRoute
  AppSchoolStudentsRoute: typeof AppSchoolStudentsRoute
  AppGymPayIdRoute: typeof AppGymPayIdRoute
  AppSchoolPayIdRoute: typeof AppSchoolPayIdRoute
  AppSchoolPayChallanIdRoute: typeof AppSchoolPayChallanIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gym/members': {
      id: '/app/gym/members'
      path: '/app/gym/members'
      fullPath: '/app/gym/members'
      preLoaderRoute: typeof AppGymMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gym/overview': {
      id: '/app/gym/overview'
      path: '/app/gym/overview'
      fullPath: '/app/gym/overview'
      preLoaderRoute: typeof AppGymOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gym/settings': {
      id: '/app/gym/settings'
      path: '/app/gym/settings'
      fullPath: '/app/gym/settings'
      preLoaderRoute: typeof AppGymSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/branches': {
      id: '/app/school/branches'
      path: '/app/school/branches'
      fullPath: '/app/school/branches'
      preLoaderRoute: typeof AppSchoolBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/custom-billing': {
      id: '/app/school/custom-billing'
      path: '/app/school/custom-billing'
      fullPath: '/app/school/custom-billing'
      preLoaderRoute: typeof AppSchoolCustomBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/fee-structures': {
      id: '/app/school/fee-structures'
      path: '/app/school/fee-structures'
      fullPath: '/app/school/fee-structures'
      preLoaderRoute: typeof AppSchoolFeeStructuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/overview': {
      id: '/app/school/overview'
      path: '/app/school/overview'
      fullPath: '/app/school/overview'
      preLoaderRoute: typeof AppSchoolOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/payments': {
      id: '/app/school/payments'
      path: '/app/school/payments'
      fullPath: '/app/school/payments'
      preLoaderRoute: typeof AppSchoolPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/reminders': {
      id: '/app/school/reminders'
      path: '/app/school/reminders'
      fullPath: '/app/school/reminders'
      preLoaderRoute: typeof AppSchoolRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/settings': {
      id: '/app/school/settings'
      path: '/app/school/settings'
      fullPath: '/app/school/settings'
      preLoaderRoute: typeof AppSchoolSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/students': {
      id: '/app/school/students'
      path: '/app/school/students'
      fullPath: '/app/school/students'
      preLoaderRoute: typeof AppSchoolStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gym/pay/$id': {
      id: '/app/gym/pay/$id'
      path: '/app/gym/pay/$id'
      fullPath: '/app/gym/pay/$id'
      preLoaderRoute: typeof AppGymPayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/pay/$id': {
      id: '/app/school/pay/$id'
      path: '/app/school/pay/$id'
      fullPath: '/app/school/pay/$id'
      preLoaderRoute: typeof AppSchoolPayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/school/pay/challan/$id': {
      id: '/app/school/pay/challan/$id'
      path: '/app/school/pay/challan/$id'
      fullPath: '/app/school/pay/challan/$id'
      preLoaderRoute: typeof AppSchoolPayChallanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppGymMembersRoute: AppGymMembersRoute,
  AppGymOverviewRoute: AppGymOverviewRoute,
  AppGymSettingsRoute: AppGymSettingsRoute,
  AppSchoolBranchesRoute: AppSchoolBranchesRoute,
  AppSchoolCustomBillingRoute: AppSchoolCustomBillingRoute,
  AppSchoolFeeStructuresRoute: AppSchoolFeeStructuresRoute,
  AppSchoolOverviewRoute: AppSchoolOverviewRoute,
  AppSchoolPaymentsRoute: AppSchoolPaymentsRoute,
  AppSchoolRemindersRoute: AppSchoolRemindersRoute,
  AppSchoolSettingsRoute: AppSchoolSettingsRoute,
  AppSchoolStudentsRoute: AppSchoolStudentsRoute,
  AppGymPayIdRoute: AppGymPayIdRoute,
  AppSchoolPayIdRoute: AppSchoolPayIdRoute,
  AppSchoolPayChallanIdRoute: AppSchoolPayChallanIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
